# Generated by Django 5.1.2 on 2024-11-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='report_status',
            field=models.CharField(choices=[('REPORTED', 'Отчет сдан'), ('UNREPORTED', 'Отчет не сдан')], default='UNREPORTED', max_length=10, verbose_name='Статус отчета'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Оплачено'), ('UNPAID', 'Неоплачено'), ('TRIAL', 'Пробный урок')], default='UNPAID', max_length=10, verbose_name='Статус оплаты'),
        ),
    ]
