# Generated by Django 5.1.2 on 2024-11-06 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_mentor_report_status_mentor_user'),
        ('info_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='students', to='info_system.achievement', verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info_system.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Оплачено'), ('UNPAID', 'Неоплачено'), ('TRIAL', 'Пробный урок')], default='UNPAID', max_length=10, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
