# Generated by Django 5.1.2 on 2024-11-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_mentor_report_status_studentuser_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='assigned_groups',
        ),
    ]
