# Generated by Django 5.1.2 on 2024-11-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_mentor_assigned_groups'),
        ('info_system', '0002_remove_group_manager_group_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='assigned_mentors', to='info_system.group', verbose_name='Назначенные группы'),
        ),
    ]
