# Generated by Django 5.1.2 on 2024-11-03 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_mentor_assigned_groups'),
        ('info_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='manager',
        ),
        migrations.AddField(
            model_name='group',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='auth_app.mentor', verbose_name='Ментор'),
        ),
    ]
